import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `sanity typegen generate` (run from the Studio) —
    // rewritten wholesale on every run, never hand-edited.
    "lib/sanity/sanity.types.ts",
    // The Studio is its own separate app nested in this folder, with
    // its own package.json, tsconfig, and eslint config
    // (@sanity/eslint-config-studio) — lint it with its own `npm run
    // lint` from inside studio-bowdoin-ai-impact/, not this one.
    "studio-bowdoin-ai-impact/**",
  ]),
]);

export default eslintConfig;
